# Silnik

- WOS 175/L SILNIK WYSOKOPRĘŻNY QSB6,7-C240 CUMMINS praca od 21.05.2019 do 11.02.2021,
- LK3 045/L SILNIK TCD2013L062V praca od 21.05.2019 do 04.03.2021,
- LK3 050/L SILNIK TCD2013L062V praca od 11.09.2019 do 19.05.2020,

In [1]:
import pandas as pd

import datetime
import pyarrow

## SILNIK 175/L

In [2]:
df = pd.read_parquet('../data/SILNIK_175L_2021_01.parquet', engine='pyarrow')
df.head(3)

,maszyna,data,czas,engoilp,enghours,fuelus,intakep,intaket,trnlup,groilp,...,breakp,hyddrv,trnaut,hydoilt,hydoilp,tempin,engrpm,engcoolt,engtps,trnbps
0,KLDSMG_WOS___175L,2021/01/01,00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,KLDSMG_WOS___175L,2021/01/01,01:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,KLDSMG_WOS___175L,2021/01/01,01:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_wos174 = pd.DataFrame(columns=df.columns)

for file_date in ['2020_10','2020_11','2020_12','2021_01','2021_02']:
    df_tmp = pd.read_parquet('../data/SILNIK_175L_' + file_date + '.parquet', engine='pyarrow')
    df_wos174 = pd.concat([df_wos174, df_tmp], axis=0)

In [4]:
df_wos174_copy = df_wos174.copy()

In [8]:
df_wos174.head(10)

,maszyna,data,czas,engoilp,fuelus,intakep,intaket,trnlup,groilp,groilt,...,breakp,hyddrv,hydoilt,hydoilp,tempin,engrpm,engcoolt,engtps,trnbps,dt
19179,KLDSMG_WOS___175L,2021/02/11,12:33:42.000,0.0,0.0,0.0,47.0,0.0,0.0,44.0,...,10000.0,0.0,52.0,0.0,25.0,0.0,87.0,0.0,0.0,2021-02-11 12:33:42
19180,KLDSMG_WOS___175L,2021/02/11,12:33:27.000,0.0,0.0,0.0,47.0,0.0,0.0,44.0,...,10000.0,0.0,52.0,0.0,25.0,0.0,87.0,0.0,0.0,2021-02-11 12:33:27
19181,KLDSMG_WOS___175L,2021/02/11,12:33:12.000,0.0,0.0,0.0,47.0,0.0,0.0,44.0,...,10000.0,0.0,52.0,0.0,25.0,0.0,87.0,0.0,0.0,2021-02-11 12:33:12
19182,KLDSMG_WOS___175L,2021/02/11,12:32:57.000,0.0,0.0,0.0,47.0,0.0,0.0,44.0,...,10000.0,0.0,52.0,0.0,25.0,0.0,87.0,0.0,0.0,2021-02-11 12:32:57
19183,KLDSMG_WOS___175L,2021/02/11,12:32:42.000,0.0,0.0,0.0,47.0,0.0,0.0,45.0,...,10000.0,0.0,52.0,0.0,25.0,0.0,87.0,0.0,0.0,2021-02-11 12:32:42
19184,KLDSMG_WOS___175L,2021/02/11,12:32:27.000,0.0,0.0,0.0,47.0,0.0,0.0,45.0,...,10000.0,0.0,52.0,0.0,25.0,0.0,87.0,0.0,0.0,2021-02-11 12:32:27
19185,KLDSMG_WOS___175L,2021/02/11,12:32:12.000,0.0,0.0,0.0,47.0,0.0,0.0,45.0,...,10000.0,0.0,52.0,0.0,25.0,0.0,87.0,0.0,0.0,2021-02-11 12:32:12
19186,KLDSMG_WOS___175L,2021/02/11,12:31:57.000,0.0,0.0,0.0,47.0,0.0,0.0,45.0,...,10000.0,0.0,52.0,0.0,25.0,0.0,87.0,0.0,0.0,2021-02-11 12:31:57
19187,KLDSMG_WOS___175L,2021/02/11,12:31:42.000,0.0,0.0,0.0,47.0,0.0,0.0,45.0,...,10000.0,0.0,52.0,0.0,25.0,0.0,87.0,0.0,0.0,2021-02-11 12:31:42
19188,KLDSMG_WOS___175L,2021/02/11,12:31:27.000,0.0,0.0,0.0,47.0,0.0,0.0,45.0,...,10000.0,0.0,52.0,0.0,25.0,0.0,87.0,0.0,0.0,2021-02-11 12:31:27

In [7]:
df_wos174 = df_wos174_copy.copy()

#zmienna wróżka; bo jest narastająca, zatem jak blisko konkretnej daty się psują to jest tu zakodowane info o statusie
df_wos174 = df_wos174.drop(columns=['enghours'])

#mało wartości
df_wos174 = df_wos174.drop(columns=['trnaut'])

#cleaning if all values are NaN
#https://stackoverflow.com/questions/13413590/how-to-drop-rows-of-pandas-dataframe-whose-value-in-a-certain-column-is-nan
df_wos174 = df_wos174.dropna(thresh=len(df_wos174.columns)-3) 

#datatime column
df_wos174['dt'] = pd.to_datetime(df_wos174['data'] + ' ' + df_wos174['czas'])
df['data'] = df['data'].astype('datetime64[ns]')

#sorting descending by date
df_wos174 = df_wos174.sort_values(by=['dt'], ascending = False).reset_index(drop=True)

#delete observations after failure
df_wos174 = df_wos174[df_wos174['dt']<'2021-02-12']

#prepare aggregats
df_wos174_1min = df_wos174.resample('1min', on='dt').mean().reset_index().set_index('dt').fillna(method='bfill')
df_wos174_1hour = df_wos174.resample('1H', on='dt').mean().reset_index().set_index('dt').fillna(method='bfill')
df_wos174_1day = df_wos174.resample('1D', on='dt').mean().reset_index().set_index('dt').fillna(method='bfill')

In [13]:
# tworzymy cechy 6h wcześniej, 12h wcześniej 24h wcześniej 48h wcześniej, 7dni wcześniej
# i agregaty mean (jak pyknie dodamy min i max)

df_tmp_6h = df_wos174_1hour.rolling(6).mean()
df_tmp_6h.columns = ['avg6_'+ col for col in list(df_tmp_6h.columns)]

df_tmp_12h = df_wos174_1hour.rolling(12).mean()
df_tmp_12h.columns = ['avg12_'+ col for col in list(df_tmp_12h.columns)]

df_tmp_24h = df_wos174_1hour.rolling(24).mean()
df_tmp_24h.columns = ['avg24_'+ col for col in list(df_tmp_24h.columns)]

df_tmp_48h = df_wos174_1hour.rolling(48).mean()
df_tmp_48h.columns = ['avg48_'+ col for col in list(df_tmp_48h.columns)]

df_tmp_168h = df_wos174_1hour.rolling(168).mean()
df_tmp_168h.columns = ['avg168_'+ col for col in list(df_tmp_168h.columns)]

In [16]:
df_wos174_1hour_hist = pd.concat([df_wos174_1hour, df_tmp_6h, df_tmp_12h, df_tmp_24h, df_tmp_48h, df_tmp_168h],axis=1)

In [17]:
df_wos174_1hour_hist

,engoilp,fuelus,intakep,intaket,trnlup,groilp,groilt,selgear,speed,breakp,...,avg168_speed,avg168_breakp,avg168_hyddrv,avg168_hydoilt,avg168_hydoilp,avg168_tempin,avg168_engrpm,avg168_engcoolt,avg168_engtps,avg168_trnbps
dt,,,,,,,,,,,,,,,,,,,,,
2020-10-01 07:00:00,111.598684,4.953947,23.789474,37.414474,0.092105,557.052632,33.230263,0.677632,1.828947,7425.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-10-01 08:00:00,119.658333,1.779167,6.766667,40.091667,0.008333,586.200000,34.375000,0.350000,0.841667,6967.083333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-10-01 09:00:00,22.320833,0.145833,0.150000,42.345833,0.000000,112.400000,30.137500,0.000000,0.000000,9486.250000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-10-01 10:00:00,0.000000,0.000000,0.000000,44.000000,0.000000,0.000000,28.000000,0.000000,0.000000,9965.416667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-10-01 11:00:00,49.600000,0.512500,0.900000,41.029167,0.004167,241.600000,29.195833,0.100000,0.237500,8700.416667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-02-11 08:00:00,207.589286,9.508929,26.473214,36.473214,0.214286,1024.642857,35.218750,1.017857,3.459821,5186.160714,...,3.146974,3896.087136,0.0,43.286575,1.283138,24.269185,891.916772,82.376949,25.686163,7.324430
2021-02-11 09:00:00,372.000000,17.783333,45.391667,49.308333,0.400000,1837.533333,62.666667,0.850000,5.104167,1383.750000,...,3.177356,3848.093883,0.0,43.425464,1.289491,24.243673,900.693829,82.743992,25.998763,7.460938
2021-02-11 10:00:00,372.000000,17.275000,42.458333,48.695833,0.462500,1841.000000,70.079167,1.237500,5.758333,943.333333,...,3.207937,3823.552712,0.0,43.607930,1.296595,24.219169,906.960322,82.883848,26.330509,7.542585
2021-02-11 11:00:00,186.620833,7.541667,14.141667,46.412500,0.225000,914.733333,63.379167,0.741667,2.774059,5339.166667,...,3.221249,3853.498149,0.0,43.721372,1.297203,24.222046,904.636389,82.887965,26.412106,7.561484
2021-02-11 12:00:00,0.000000,0.000000,0.000000,47.000000,0.000000,0.000000,49.651852,0.000000,0.000000,10011.111111,...,3.220158,3867.987763,0.0,43.800253,1.296208,24.232039,903.081673,82.877542,26.392611,7.553218

In [8]:
df_wos174_1hour_hist = df_wos174_1hour_hist.reset_index()
# status good / bad. If 2 weeks before failture then bad else good

df_wos174_1hour_hist['status'] = df_wos174_1hour_hist['dt'].apply(lambda x: 0 if x < datetime.datetime(2021,2,12)-datetime.timedelta(days=14) else 1)

# buffor - 2 weeks between good and bads
df_wos174_1hour_hist['buffor'] = df_wos174_1hour_hist['dt'].apply(lambda x: 1 if x < datetime.datetime(2021,2,12)-datetime.timedelta(days=30) else 0)

# not longer then 3 months before failure
df_wos174_1hour_hist['notLonger'] = df_wos174_1hour_hist['dt'].apply(lambda x: 0 if x < datetime.datetime(2021,2,12)-datetime.timedelta(days=90) else 1)

In [9]:
df_wos174_1hour_hist_final = pd.concat([df_wos174_1hour_hist[df_wos174_1hour_hist['status']==1],
                                        df_wos174_1hour_hist[(df_wos174_1hour_hist['status']==0) & (df_wos174_1hour_hist['buffor']==1) & (df_wos174_1hour_hist['notLonger']==1)]
                                       ], axis=0)

print(f'shape: {df_wos174_1hour_hist_final.shape}')

df_wos174_1hour_hist_final.status.value_counts()

shape: (1765, 112)

0    1440
1     325
Name: status, dtype: int64

In [10]:
#df_wos174_1hour_hist_final = df_wos174_1hour_hist_final.drop(columns=['index']).iloc[:,1:-2].reset_index(drop=True)
df_wos174_1hour_hist_final = df_wos174_1hour_hist_final.iloc[:,1:-2].reset_index(drop=True)
df_wos174_1hour_hist_final.head(3)

,engoilp,fuelus,intakep,intaket,trnlup,groilp,groilt,selgear,speed,breakp,...,avg168_breakp,avg168_hyddrv,avg168_hydoilt,avg168_hydoilp,avg168_tempin,avg168_engrpm,avg168_engcoolt,avg168_engtps,avg168_trnbps,status
0,272.800000,16.245833,69.766667,63.541667,0.400000,1358.933333,69.229167,1.120833,4.4625,3030.416667,...,3489.344466,0.0,53.717838,0.719142,25.515022,1043.244605,83.326418,32.199887,6.188123,1
1,372.000000,19.770833,84.475000,64.337500,0.437500,1847.666667,72.375000,1.266667,5.2125,623.333333,...,3489.979387,0.0,53.713126,0.717994,25.504581,1044.604674,83.330858,32.275284,6.216818,1
2,371.691667,18.895833,73.791667,63.525000,0.316667,1832.733333,72.183333,1.004167,3.7750,791.250000,...,3491.603891,0.0,53.720343,0.717663,25.490494,1044.627244,83.334851,32.277739,6.263172,1

In [11]:
df_wos174_1hour_hist_final.to_csv('../data/df_silnik175.csv', sep="|", index=False)